steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/tokyo-ceiling-435523-d0/ica4-frontend:$SHORT_SHA', './frontend' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/tokyo-ceiling-435523-d0/ica4-frontend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/frontend-deployment', 'frontend-container=gcr.io/tokyo-ceiling-435523-d0/ica4-frontend:$SHORT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
logsBucket: 'gs://ica4-frontend-build-logs'

